name: "Build"

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Run build
      run: cmd /c build.bat
    - name: Upload artiacts
      uses: actions/upload-artifact@v4
      with:
        name: pgwin_deps-${github.ref}
        path: out
        retention-days: 1
